name: Build PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://exaesmwp4/texlive:latest
    steps:
    - uses: actions/checkout@v2
    - run: cd $GITHUB_WORKSPACE/tex/ && latexmk -pdf -pdflatex='pdflatex --shell-escape' example.tex
